issues/101
adaptlearning/adapt-contrib-xapi pull request #102
Opened 2021-12-08 13:03 UTC by cahirodoherty-learningpool

fixes #101 

Swapped out Async.each for a for/in loop to resolve async/await issues

2021-12-08 13:10 UTC, eleanor-heath approved these changes

2021-12-08 14:31 UTC, ethan-lp approved these changes

2021-12-08 15:21 UTC, oliverfoster commented
Did it fix the problem? I can't see how the code is different from before, with the exception of https://github.com/adaptlearning/adapt-contrib-xapi/pull/102/files#diff-b0b5ab3ca1ad9e3f2e6a5f7f072256b8d933fdcdb7f6b929fd463257fde05229R1130 `if (!_.isEmpty(state)) {`

2021-12-08 15:32 UTC, cahirodoherty-learningpool commented
> 

Hi Oli, yeah this fixed the issue. The await is now being respected and the state is getting populated correctly. I'll remove the async library here now

2021-12-08 17:36 UTC, cahirodoherty-learningpool commented
@oliverfoster The Async library has now been removed

2021-12-08 17:41 UTC, oliverfoster commented on js/XAPI.js
> +      await new Promise((resolve, reject) => {
Bad indentation inside this promise code block.

2021-12-08 17:42 UTC, oliverfoster requested changes

2021-12-08 17:42 UTC, oliverfoster commented on js/XAPI.js
> +        resolve();
you'll have to return here otherwise it'll carry on into the attachment.url block

2021-12-08 17:42 UTC, oliverfoster commented on js/XAPI.js
> +      await new Promise((resolve, reject) => {
bad indentation inside the promise code block

2021-12-10 11:35 UTC, cahirodoherty-learningpool commented
@oliverfoster Indentation and return of resolve now fixed

2021-12-10 12:03 UTC, oliverfoster approved these changes

2021-12-10 12:03 UTC, merged